TELEGRAM_BOT_TOKEN = "Enter your bot token"
TELEGRAM_CHAT_ID = "Enter your chat ID"  
WEBHOOKS_PORTS = "Enter your webhooks port"
URL_NETBOX = "Enter your URL NETBOX"
TOKEN_NETBOX = "Enter your Token NETBOX"